### ISSUE TITLE
Question About Problem 4

### ISSUE THREAD

**Issue by tjp36** [uchicago-bio/2016-Autumn-Forum#12]
For problem 4, how should we handle the case of Y --> T C (pyrimidine) ?  For example, in one of the sequences in the file that was provided, one of the bases is Y, which as I understand it means the base could be T or C.  Should we just ignore this base for G-C content purposes since it could be either?  Any guidance would be appreciated.

Thanks,

Ted

**Comment by tabinks** [comment]
@tjp36 Are you sure you are reading the correct file?  
http://uchicago.bio/sessions/session1/multiple_DNA.fasta.txt  

I'm not seeing any "Y".

**Comment by tjp36** [comment]
I think I am reading it right.  In the file you provided in the link, find the following line:

> gi|51989218|gb|AY724960.1| Homo sapiens chromosome 7 taste receptor T2R38 gene, complete cds

In that sequence, go to line 10 (counting from 1).  Look 16 characters from the right on that line.  I see a Y.  For reference, the line is:

GCCCACATTAAAGCCCTCAAGTCTCTTGTCTCCTTTTTCTGCTTCTTTGTGATATCATCCTGTG**Y**TGCCTTCATCTCTGT

**Comment by tabinks** [comment]
@tjp36 So it appears, I was looking at the wrong file.  

Yes, for the purpose of C-G content, you can ignore it since we don't know what it is.
