### ISSUE TITLE
One more question about reading frames

### ISSUE THREAD

**Issue by tjp36** [uchicago-bio/2016-Autumn-Forum#14]
I think I know the answer to this question, but I just want to make sure.

Say I have an amino acid sequence that is MIKSMST*.

There would be two reading frames here correct?  One would be MIKSMST, while the other would be MST.

Is this right?

**Comment by tabinks** [comment]
Yes.  That is correct.  A sequence may have multiple coding regions as long as they meet the criteria:
- Start codon (M)
- Amino acids in between
- Stop codon
