### ISSUE TITLE
Question About HW2 Question 8

### ISSUE THREAD

**Issue by tjp36** [uchicago-bio/2016-Autumn-Forum#15]
The last question of this week's homework has two cells to input answers.  However, I don't quite see why there would be two answers for this question.  Right now, I copy and pasted the web address of my deployed application in one of the cells.  Was the second cell included in error?  If not, what should we put in it?

Thanks,

Ted

**Comment by tabinks** [comment]
There is only supposed to be one cell.  I've noticed that sometimes a cell is automatically created once you run the last cell in a notebook.  Just ignore it.

**Comment by tjp36** [comment]
thanks
