### ISSUE TITLE
Link in Question 4 Dead

### ISSUE THREAD

**Issue by tjp36** [uchicago-bio/2016-Autumn-Forum#18]
The link in Question 4 (the Jurassic Park question) does not appear to be working.  Is there an alternative site we can find to download the sequence?

Thanks,

Ted

**Comment by tabinks** [comment]
http://uchicago.bio/sessions/session2/dino-dna-lost-world.fa.txt

**Comment by tjp36** [comment]
Thanks

**Comment by tabinks** [comment]
@uchicago-bio/mpcs56420-2016-autumn I fixed the link.

**Comment by tjp36** [comment]
I was using the version that was posted Monday.  That explains it.

**Comment by tabinks** [comment]
Ok.  Just wanted to make sure I fixed it.
