### ISSUE TITLE
Homework Note

### ISSUE THREAD

**Issue by jvmakin** [uchicago-bio/2016-Autumn-Forum#19]
Hey Team,

I'm working on grading assignment one (grades by next class at the lastest!) and I have noticed that a few of you don't seem to be running your code in the notebooks. While I understand that a new developing environment can be annoying to adjust to and that there were some issues this week getting your notebooks up and running, **in future please make sure all code is self contained within the notebooks.** You should run it yourself in that environment to make sure it works!

Also, while this is not mandatory, it would be helpful if you included the test files you used. This helps me to see whether any issues are coming from your code or an error in your file.

Thank you!

**Comment by tabinks** [comment]
If anyone has questions about running in notebooks, please ask...

**Comment by castuardo** [comment]
Hey guys,

Is there a repository for HW2?

Kind regards

**Comment by tabinks** [comment]
@castuardo See #16

**Comment by castuardo** [comment]
Thx!!!
