### ISSUE TITLE
Bio News of the Week 1

### ISSUE THREAD

**Issue by tabinks** [uchicago-bio/2016-Autumn-Forum#2]
[Microsoft's "Biological Computing" Lab Aims To Fight Diseases By Reprogramming Cells | Fast Company | Business + Innovation](https://www.fastcompany.com/3063835/mind-and-machine/microsofts-biological-computing-lab-wants-to-fight-diseases-by-reprogrammin)

**Comment by tjp36** [comment]
http://www.technicianonline.com/news/article_132e2434-845e-11e6-ab8a-5bc8777550ef.html

**Comment by jefftempus** [comment]
Shameless coverage for my employer :) Genomics getting  some action here in Chicago:

http://www.chicagobusiness.com/article/20160929/BLOGS11/160929779/lefkofsky-takes-on-the-big-c

**Comment by grantcupps** [comment]
http://www.nytimes.com/2016/10/04/science/yoshinori-ohsumi-nobel-prize-medicine.html?_r=0

**Comment by fungedwin** [comment]
http://www.the-scientist.com/?articles.view/articleNo/47153/title/DNA-Sequencing--From-Tedious-to-Automatic/

**Comment by rdb57** [comment]
Less about bioinformatics directly and more about genes, drugs, and the need for better understanding of drug site binding.

http://phys.org/news/2016-09-drug-products-affect-entire-biological.html

**Comment by ZJMEI** [comment]
http://www.asianscientist.com/2016/09/topnews/china-national-gene-bank-bgi-genomics/

**Comment by castuardo** [comment]
https://www.ncbi.nlm.nih.gov/pubmed/25768907

**Comment by anuvedverma** [comment]
http://www.nature.com/articles/cddiscovery201668
