### ISSUE TITLE
Question 1: First Author Publications

### ISSUE THREAD

**Issue by grantcupps** [uchicago-bio/2016-Autumn-Forum#20]
Could you elaborate on "first author publications"?  I assume that it means publications where he is listed as the first author, but do publications include drafts, dissertations, patents, etc?  Or should we limit ourselves to items published in journals?

**Comment by tabinks** [comment]
Limit this to publications, where he is listed as the first author.  The first author is typically the one who did most of the work and it responsible for the research.  The other authors are ones who contributed in some smaller way.
