### ISSUE TITLE
Assignment 1 Resubmissions

### ISSUE THREAD

**Issue by tabinks** [uchicago-bio/2016-Autumn-Forum#21]
For those of you who would like the opportunity to go back and address some of the issues in your Assignment 1, we will accept resubmissions until Thursday October 13th at 11:59PM.

**Comment by jvmakin** [comment]
It would also be very helpful if you emailed me to let me know if you're resubmitting; that way I don't miss anyone!

**Comment by anuvedverma** [comment]
I couldn't find your guys' email addresses on the website/syllabus, so just letting you know I've resubmitted the first assignment. There are some clarification questions/notes in the README, so please check that too!

**Comment by tabinks** [comment]
@anuvedverma Thanks.  It's abinkowski@uchicago.edu

**Comment by jvmakin** [comment]
Mine is: jvmakin@uchicago (for future reference :) )
