### ISSUE TITLE
Error 503 first byte timeout

### ISSUE THREAD

**Issue by grantcupps** [uchicago-bio/2016-Autumn-Forum#23]
When I try to get the Jupyter notebook for this week's assignment, I get a `503` error.  Is the notebook available elsewhere?

**Comment by tabinks** [comment]
Actually, I'm seeing the entire site down.  I'm going to blame it on github pages.  I'm investigating now.

**Comment by tabinks** [comment]
@uchicago-bio/mpcs56420-2016-autumn There is a DDoS attack going on at Hover (domain registrar) so the web site is down.

Here is the assignment file:

[MPCS56420-2016-Autumn-Assignment3.ipynb.zip](https://github.com/uchicago-bio/2016-Autumn-Forum/files/525712/MPCS56420-2016-Autumn-Assignment3.ipynb.zip)

**Comment by tabinks** [comment]
Thanks @grantcupps for the heads up.
