### ISSUE TITLE
Bio News of the Week 4

### ISSUE THREAD

**Issue by jvmakin** [uchicago-bio/2016-Autumn-Forum#28]
The first three minutes of this are about battling cancer and some of the problems with 'big data'. Really amazing to see this issue on the forefront!

http://www.npr.org/2016/10/17/498292027/vice-president-biden-what-trump-is-doing-is-very-dangerous

**Comment by rdb57** [comment]
http://phys.org/news/2016-10-molecular-evolutionary-unpredictable.html
