### ISSUE TITLE
Assignment 4 Repo and RCC Accounts

### ISSUE THREAD

**Issue by tabinks** [uchicago-bio/2016-Autumn-Forum#29]
Repo: https://classroom.github.com/assignment-invitations/287b1b6a6889885960328fb09be3bc77

Assignment: http://uchicago.bio/sessions/session4/MPCS56420-2016-Autumn-Assignment4.ipynb

I've got word that your RCC accounts will be activated tomorrow.  I will post here with instructions on how to login.

**Comment by tabinks** [comment]
## Log in to RCC
- From a terminal login using ssh

```
ssh <cnetid>@midway.rcc.uchicago.edu
```

## Download Files
- Query sequence file

```
wget http://uchicago.bio/sessions/session4/protein1.fasta
```
- Sbatch script to launch a blastp job on a single node.  Note that it uses a database that is located on a shared directory on RCC.

```
wget https://raw.githubusercontent.com/uchicago-bio/RCC-Utilities/master/single-node-blast.sbatch
```

## Run the Script

From the command line:

```
sbatch single-node-blast.sbatch <some-unique-text-to-identify-this-job>
```

## Adjust the number of threads

This task is running on a single node, but we will vary the number of threads that are used.  Do runs with 1,2,4,8,16 threads.  The Sandy Bridge chips in our allocation have 16 cores.

```
#SBATCH --cpus-per-task=1
```

**Comment by fungedwin** [comment]
Might be too early, but I'm still having trouble logging into RCC, it says permission denied after I try to enter my password.

**Comment by tabinks** [comment]
@fungedwin I'm looking into it.
