### ISSUE TITLE
Office Hours/Homework Note

### ISSUE THREAD

**Issue by jvmakin** [uchicago-bio/2016-Autumn-Forum#31]
Hey Kittens,

It's that time again! I will be hosting office hours at 3:30 PM today in Young 306 provided people are planning on attending. Please let me know, ideally before 2:30ish...I have not yet mastered the art of teleportation. :)

Also, if you would prefer later office hours or downtown office hours, let me know.

On the homework front, HW 1 and 2 should have grades/regrades for everyone. There was vast improvement between the first and second iterations of HW1, so YAY! Let me know if you haven't received a grade/regrade.

**Comment by fungedwin** [comment]
Hi Jane,

I plan on attending office hours but would prefer a later time (today), and/or downtown if possible.

**Comment by jvmakin** [comment]
Would 6PM at the Gleacher center work?

Also, would this change prevent anyone from coming?

**Comment by fungedwin** [comment]
6PM at Gleacher would be great!

**Comment by jvmakin** [comment]
Barring any massive dissent, see you then!
