### ISSUE TITLE
Trouble SSHing to RCC

### ISSUE THREAD

**Issue by tjp36** [uchicago-bio/2016-Autumn-Forum#35]
I am having a problem SSHing into the RCC.  I have previously SSH'd into U. Chicago systems before.  In fact, when I SSH in via tjp36@linux.cs.uchicago.edu, I connect successfully.  However, when I use ssh tjp36@midway.rcc.uchicago.edu to log into the RCC, I get the following message:

`ssh_exchange_identification: read: Connection reset by peer`

When I run the above in verbose mode, ssh tjp36@midway.rcc.uchicago.edu -vv, I get the following:

`OpenSSH_6.9p1, LibreSSL 2.1.8
debug1: Reading configuration data /Users/theodoreprekop/.ssh/config
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 21: Applying options for *
debug1: /etc/ssh/ssh_config line 56: Applying options for *
debug2: ssh_connect: needpriv 0
debug1: Connecting to midway.rcc.uchicago.edu [128.135.112.71] port 22.
debug1: Connection established.
debug1: identity file /Users/theodoreprekop/.ssh/id_rsa type 1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/theodoreprekop/.ssh/id_rsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/theodoreprekop/.ssh/id_dsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/theodoreprekop/.ssh/id_dsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/theodoreprekop/.ssh/id_ecdsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/theodoreprekop/.ssh/id_ecdsa-cert type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/theodoreprekop/.ssh/id_ed25519 type -1
debug1: key_load_public: No such file or directory
debug1: identity file /Users/theodoreprekop/.ssh/id_ed25519-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_6.9
ssh_exchange_identification: read: Connection reset by peer`

Any Idea what is going on?

EDIT:  From the RCC website, it appears that if you have 10 bad password attempts, a 4 hour block is placed on your IP address.  I guess I will try again in 4 hours....  Our password is our cnet password correct?  I was positive I was entering my CNET password in correctly (I tested this by logging into the Student Center), but it was not accepting my password.

**Comment by tabinks** [comment]
@tjp36 I filed a support ticket with RCC.  That sounds more like a problem on their end.  There is probably a good chance that they won't resolve it until tomorrow.  In the meantime, you can spend the day convincing yourself that the Indians are going to win.

**Comment by tjp36** [comment]
Haha.  Thanks.  I figured they wouldn't be able to get to it until tomorrow.

I was quite surprised when FOX and ABC cut away from the College Football games last night to show Cubs celebrations for winning NLCS.  It's not like they won the World Series!
