### ISSUE TITLE
/project/databases/blast/ permission denied?

### ISSUE THREAD

**Issue by castuardo** [uchicago-bio/2016-Autumn-Forum#38]
Hey,
My array job is giving me errors (file not found) and i realized that i dont have permission to see this dir.

**Comment by tabinks** [comment]
Did you try running it?  The nodes running the job should be able to see the director.

**Comment by castuardo** [comment]
yep, i ran the sbatch file, but it reports that "was not able to access the file, no such file or directory"

**Comment by tabinks** [comment]
I copied the database over to
`/project/mpcs56420/nr/`

Use this range instead: 

```
/project/mpcs56420/nr/nr.00
/project/mpcs56420/nr/nr.01
/project/mpcs56420/nr/nr.02
...
```

**Comment by castuardo** [comment]
great!. I enqueued the job, ill let you know if u have problems again.
Thx!

**Comment by castuardo** [comment]
yep, seems to be running fine. Ill close this.
Thx

**Comment by tabinks** [comment]
Glad to hear it.
