### ISSUE TITLE
Password for RCC Cluster

### ISSUE THREAD

**Issue by tjp36** [uchicago-bio/2016-Autumn-Forum#40]
I am still having issues SSHing into the RCC.  Specifically, it won't accept my password.  I am 100% positive the password I am entering is my CNET password.  I tested this by logging into the UChicago portal (the places where you pay tuition and view grades) with my password and I was able to successfully log into the portal.  When I type the exact same password at the SSH prompt, I get a "Permission denied, please try again."  I don't want to continue to password spam because I don't want to get locked out again for another 4 hours.  

This leads me to 2 possible conclusions:  either my account was not setup properly or the password I am supposed to use is not in fact my CNET password.  Any idea whats going on?

Thanks,

Ted

**Comment by tabinks** [comment]
I sent an email to my contact last night, but I haven't heard back.  

Fill out this form with your info and see if some gets in touch with your first:
https://rcc.uchicago.edu/support-and-services/consulting-and-technical-support

**Comment by tjp36** [comment]
Apparently my account was never created.  I filled out the form to request an account.  We will see how long it will take to get an account.

**Comment by tjp36** [comment]
I have access.
