### ISSUE TITLE
Assignment 5 Repo and Links

### ISSUE THREAD

**Issue by tabinks** [uchicago-bio/2016-Autumn-Forum#43]
Repo: https://classroom.github.com/assignment-invitations/ca00923eba034e8b92cfc9fa325c3632

RCC Utilities on Github: https://github.com/uchicago-bio/RCC-Utilities

**Comment by fungedwin** [comment]
@tabinks can you post the link to Lecture 5 slides as well?  Thanks!

**Comment by tabinks** [comment]
@fungedwin Sorry, there up there now.
