### ISSUE TITLE
HW5-1 slurm script giving FAILED, Exit Code 1

### ISSUE THREAD

**Issue by anuvedverma** [uchicago-bio/2016-Autumn-Forum#45]
I tried running an mpiBLAST job in RCC but the script keeps failing... was wondering if you could point out which step I might have messed up on.

Here's the error code that got emailed to me:
`SLURM Job_id=20879573 Name=mpi-blast Failed, Run time 00:00:07, FAILED, ExitCode 1`
Looking at the error code output, it says `APPLICATION TERMINATED WITH THE EXIT STRING: Hangup (signal 1)`.

Here's what I did so far after logging onto the RCC cluster:

0) Copied the `protein1.fasta` file into my `/home/anuvedverma/` directory

1) Copied the .ncbirc text from `https://github.com/uchicago-bio/RCC-Utilities/wiki/Running-mpiBlast-at-RCC` into `av.ncbirc` in my `home/anuvedverma/` directory (does the name of the `.ncbirc` file matter here?)

2) Edited the .ncbirc file to replace all instances of `abinkowski` with my cnet-id, `anuvedverma`

3) Setup the `/scratch/.../mpiblast/db` directories under `home/anuvedverma`. The complete directory structure now looks like: `/home/anuvedverma/scratch/midway/anuvedverma/mpiblast/db`

4)Copied the database into my scratch directory using  `cp /project/mpcs56420/databases/pdb/* scratch/midway/anuvedverma/mpiblast/db`

5) Copied the slurm script into `/home/anuvedverma` and edited it to change the email address

6) Ran the slurm script (Failed)

The only changes I made to either scripts was my CNET ID, am I missing a step somewhere in here? Let me know if it'd be easier to go over this in office hours!

Thanks,
Anuved

**Comment by tabinks** [comment]
See #46.

Yes, the file needs to be named `.ncbirc`.  Nothing before the `.`.

Keep the paths on the databases to abinkowski.  They are located there and should be able to be read by everyone.

**Comment by tabinks** [comment]
@anuvedverma Any luck?

**Comment by rdb57** [comment]
I had the same result, but it was because I didn't make the change to the database -- so that it used the files we copied to scratch.  Once I did that, it was fine.

**Comment by anuvedverma** [comment]
I think it worked! Only thing I had to change was renaming `av.ncbirc` to just `.ncbirc`. Output looks right, but the job completed in 7 seconds... is that normal (2 nodes, 8 tasks/node)? 

Also I'm still a little unclear which database we should be reading from. The script I used is using `Shared=/project/mpcs56420/databases/mpi`, but I'm also seeing `Shared=/scratch/midway/abinkowski/mpiblast/db` and `Shared=/project/mpcs56420/databases/mpiblast-nr` as options from the RCC-Utilities wiki. Also the homework says to query against `/projects/mpcs56420/nr/`. Can you clarify what the differences are?
