### ISSUE TITLE
Protein Database for Question #4

### ISSUE THREAD

**Issue by grantcupps** [uchicago-bio/2016-Autumn-Forum#47]
@tabinks, could you please post the database for question #4?  The link `http://uchicago.bio/sessions/session5/protein100.txt` doesn't seem to be working.

**Comment by tabinks** [comment]
Here are the direct links on Github:  https://github.com/uchicago-bio/RCC-Utilities/tree/master/database

**pdb1000.fasta** is 500 protein sequences (good for testing)
**pdb.fasta** is the entire protein databank of 215,148 sequences (good for burning computing time)

@grantcupps
