### ISSUE TITLE
Midterm Exam

### ISSUE THREAD

**Issue by tabinks** [uchicago-bio/2016-Autumn-Forum#50]
The exam is posted on the course website.  

This exam was designed to be taken in class, so you should plan for about 3 hours to finish it.  You can use any resources available to complete the exam (e.g. it is open book/notes/Internet).  If you have any questions, please post them to the forum.

Submit your exam using the repository before Monday, November 7th at 5:29PM.  

Exam:   http://uchicago.bio/sessions/session6/MPCS56420-MidtermExam.ipynb
Repo: https://classroom.github.com/assignment-invitations/fb339ad64053b88ac99e9543893cf8f1

Have fun :)

@uchicago-bio/mpcs56420-2016-autumn

**Comment by jvmakin** [comment]
Just as a comment, for the midterm...if you want to make a cell in jupyter app engine text (rather than code) select the cell and click the button that says code then change it to markdown. 

Hope this is helpful!

**Comment by rdb57** [comment]
I seem to get a broken image for question 6?  (Evolution.png)

**Comment by rdb57** [comment]
Oops.  I mean question 7....  Sorry.

**Comment by tabinks** [comment]
I fixed the link in the notebook.  If you have already downloaded it, then just change the URL in the notebook to `http://uchicago.bio/sessions/session6/Evolution.png`.

Or, just look here:

![evolution](https://cloud.githubusercontent.com/assets/93689/19971319/abcbce1a-a1ac-11e6-907d-fe76363d6415.png)
