### ISSUE TITLE
Fold.it down for maintenance

### ISSUE THREAD

**Issue by grantcupps** [uchicago-bio/2016-Autumn-Forum#64]
FYI, it looks like the fold.it website / game is down for maintenance.  According to the status page (http://foldit.wikia.com/wiki/Foldit_Status), it has been down since Wednesday and could be down until Monday.

**Comment by tabinks** [comment]
Well that was bad timing.  This assignment will now have the same due date at your final projects.  Take this time to work on your projects.

@uchicago-bio/mpcs56420-2016-autumn
